### ISSUE TITLE
Images are placeholder image

### ISSUE THREAD

**Issue by fkinoshita** [ekzhang/dispict#1]
All images in the museum are this placeholder image from Harvard, just to let you know in case you missed it!

![Screenshot 2023-12-30 at 03-00-45 Dispict a creative aesthetics tool](https://github.com/ekzhang/dispict/assets/126302554/7e48c9b3-8b31-4b06-b12a-9401597ca930)

**Comment by ekzhang** [comment]
Nice! Yeah I think the folks who run Harvard's IT department are having some issues over the holidays, see https://harvardartmuseums.org/collections

I don't host the images myself out of respect for copyright :)

<img width="1437" alt="image" src="https://github.com/ekzhang/dispict/assets/7550632/ce0e00aa-6870-420d-b9f4-0a0ca336fb0b">

**Comment by ekzhang** [comment]
<img width="1250" alt="image" src="https://github.com/ekzhang/dispict/assets/7550632/7af3f584-20c5-4d0c-aee5-971146ab3617">

Looks like it's mostly resolved, although still a couple images are down :)
